#!/bin/bash

OUTPUT_FILE="site.js"
BACKUP_DIR=".backup"
TEMP_FILE="${OUTPUT_FILE}.tmp"

echo "Generating bundled site.js..."

mkdir -p "${BACKUP_DIR}"

if [ -f "${OUTPUT_FILE}" ] && ! grep -q "Generated by generate-site.sh" "${OUTPUT_FILE}"; then
  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
  cp "${OUTPUT_FILE}" "${BACKUP_DIR}/site.js.${TIMESTAMP}"
  echo "  ✓ Backed up original site.js to ${BACKUP_DIR}/site.js.${TIMESTAMP}"
fi

HELPERS=(
  "helper-html.js"
  "helper-modal.js"
  "helper-menu.js"
  "helper-event.js"
  "helper-api.js"
  "helper-data.js"
  "helper-action-buttons.js"
  "helper-auth.js"
)

> "${TEMP_FILE}"

echo "// Bundled site.js - Generated by generate-site.sh at $(date '+%Y-%m-%d %H:%M:%S')" >> "${TEMP_FILE}"

for helper in "${HELPERS[@]}"; do
  if [ -f "${helper}" ]; then
    cat "${helper}" >> "${TEMP_FILE}"
    echo "  ✓ Added: ${helper}"
  else
    echo "  ✗ WARNING: ${helper} not found, skipping..."
  fi
done

echo ""
echo "Minifying JavaScript to single line..."

# Minification steps:
# 1. Remove single-line comments (preserve URLs)
# 2. Remove leading/trailing whitespace
# 3. Remove empty lines
# 4. Join all lines into one

sed -E '
  # Remove single-line comments (but not URLs like https:// or http://)
  s#^[ \t]*//.*$##
  s#[ \t]+//[^"].*$##
  # Remove leading whitespace
  s/^[ \t]+//
  # Remove trailing whitespace
  s/[ \t]+$//
  # Remove empty lines
  /^$/d
' "${TEMP_FILE}" | tr '\n' ' ' | sed -E '
  # Clean up multiple spaces (but not inside template literals)
  s/  +/ /g
  # Remove spaces around semicolons
  s/ *; */;/g
  # Remove spaces around commas
  s/ *, */,/g
  # Add final newline
  s/$/\n/
' > "${OUTPUT_FILE}"

# Clean up temp file
rm -f "${TEMP_FILE}"

echo "  ✓ Minified with sed"
echo ""
echo "✓ Successfully generated ${OUTPUT_FILE}"
echo "  File size: $(wc -c < "${OUTPUT_FILE}") bytes"
echo ""
echo "All helpers are now bundled in correct order!"
echo "HTML files can now use: <script src=\"site.js\"></script>"
