#!/bin/bash

OUTPUT_FILE="../site.js"
TEMP_FILE="${OUTPUT_FILE}.tmp"
VERSION_FILE=".site-version"
PROJECT_ROOT="../.."

echo "Generating bundled site.js..."

# Read current version or initialize to 0
if [ -f "${VERSION_FILE}" ]; then
  CURRENT_VERSION=$(cat "${VERSION_FILE}")
else
  CURRENT_VERSION=0
fi

# Increment version
NEW_VERSION=$((CURRENT_VERSION + 1))
echo "  Version: ${CURRENT_VERSION} → ${NEW_VERSION}"
echo ""

HELPERS=(
  "helper-event.js"
  "helper-html.js"
  "helper-modal.js"
  "helper-menu.js"
  "helper-api.js"
  "helper-data.js"
  "helper-image.js"
  "helper-action-buttons.js"
  "helper-auth.js"
)


> "${TEMP_FILE}"

echo "// Bundled site.js - Generated by generate-site.sh at $(date '+%Y-%m-%d %H:%M:%S')" >> "${TEMP_FILE}"

for helper in "${HELPERS[@]}"; do
  if [ -f "${helper}" ]; then
    cat "${helper}" >> "${TEMP_FILE}"
    echo "  ✓ Added: ${helper}"
  else
    echo "  ✗ WARNING: ${helper} not found, skipping..."
  fi
done

echo ""
echo "Minifying JavaScript to single line..."

# Minification steps:
# 1. Remove single-line comments (preserve URLs)
# 2. Remove leading/trailing whitespace
# 3. Remove empty lines
# 4. Join all lines into one

sed -E '
  # Remove single-line comments (but not URLs like https:// or http://)
  s#^[ \t]*//.*$##
  s#[ \t]+//[^"].*$##
  # Remove leading whitespace
  s/^[ \t]+//
  # Remove trailing whitespace
  s/[ \t]+$//
  # Remove empty lines
  /^$/d
' "${TEMP_FILE}" | tr '\n' ' ' | sed -E '
  # Clean up multiple spaces (but not inside strings)
  s/  +/ /g
  # Remove spaces around semicolons (outside strings)
  s/ *; */;/g
  # Remove space BEFORE comma only (keep space after for readability in strings)
  s/ +,/,/g
  # Add final newline
  s/$/\n/
' > "${OUTPUT_FILE}"

# Clean up temp file
rm -f "${TEMP_FILE}"

echo "  ✓ Minified with sed"
echo ""
echo "✓ Successfully generated ${OUTPUT_FILE}"
echo "  File size: $(wc -c < "${OUTPUT_FILE}") bytes"
echo ""

# Update HTML files with new version
echo "Updating script and CSS tags in HTML files..."
HTML_COUNT=0
CSS_COUNT=0

# Find all HTML files in project root
for html_file in "${PROJECT_ROOT}"/*.html; do
  if [ -f "${html_file}" ]; then
    # Update ./s/site.js references
    if grep -q 'src="./s/site\.js' "${html_file}"; then
      # Remove old version parameter if exists, then add new one
      sed -i -E 's#src="./s/site\.js(\?v=[0-9]+)?"#src="./s/site.js?v='"${NEW_VERSION}"'"#g' "${html_file}"
      ((HTML_COUNT++))
    fi

    # Update ./s/code/pages/*.js references
    if grep -q 'src="./s/code/pages/' "${html_file}"; then
      sed -i -E 's#src="(./s/code/pages/[^"]+\.js)(\?v=[0-9]+)?"#src="\1?v='"${NEW_VERSION}"'"#g' "${html_file}"
    fi

    # Update ./s/site.css references
    if grep -q 'href="./s/site\.css' "${html_file}"; then
      # Remove old version parameter if exists, then add new one
      sed -i -E 's#href="./s/site\.css(\?v=[0-9]+)?"#href="./s/site.css?v='"${NEW_VERSION}"'"#g' "${html_file}"
      ((CSS_COUNT++))
    fi
  fi
done

echo "  ✓ Updated ${HTML_COUNT} HTML files (JS)"
echo "  ✓ Updated ${CSS_COUNT} HTML files (CSS)"

# Save new version
echo "${NEW_VERSION}" > "${VERSION_FILE}"
echo "  ✓ Version saved: ${NEW_VERSION}"

echo ""
echo "All helpers are now bundled in correct order!"
echo "HTML files now use:"
echo "  <link rel=\"stylesheet\" href=\"./s/site.css?v=${NEW_VERSION}\" />"
echo "  <script src=\"./s/site.js?v=${NEW_VERSION}\"></script>"
